import '@styles/globals.css';
import { Roboto } from 'next/font/google';
import Head from 'next/head';
import { NavBar } from '@components/index';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  variable: '--font-rob',
});

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>MJ Asprec&apos;s Portfolio</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
      </Head>
      <main
        className={`${roboto.variable} font-rob bg-light w-full min-h-screen`}
      >
        <NavBar />
        <Component {...pageProps} />
      </main>
    </>
  );
}
