import Head from 'next/head';
import { Header } from '@components/index';

export default function Home() {
  return (
    <>
      <Head>
        <title>MJ Asprec&apos;s Portfolio</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <main className=''>
        <Header />
        <h1 className='text-red-500'>Hello world!</h1>
      </main>
    </>
  );
}
